
class Settings:
    """Setting used to configure the parser"""


FILE_UPLOAD_TEMP_DIR = '.'

FILE_UPLOAD_MAX_MEMORY_SIZE = 4096

DEFAULT_CHARSET = 'utf-8'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 4096

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024

WEB_PROXY = False

FILE_UPLOAD_HANDLERS = { "TODO: FIX ME" }